apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  type: LoadBalancer
  selector:
    app: finance
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
