- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image
      command: docker pull yourdockerhubid/finance-me-app:latest

    - name: Run Docker container
      command: docker run -d -p 8080:8080 yourdockerhubid/finance-me-app:latest
