- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Pull Docker image
      command: docker pull yourdockerid/finance-me-app:latest

    - name: Run Docker container
      command: docker run -d -p 8080:8080 yourdockerid/finance-me-app:latest
